# ToadGBA directory config
# Edit this file or use System > Directories in the emulator menu

rom_directory = roms

save_directory = save

save_state_directory = state

game_config_directory = cfg

snapshot_directory = ms0:/PICTURE

cheat_directory = cheat

overlay_directory = overlays
